experiment_planner/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import RedirectView
from users import views as user_views

urlpatterns = [
    path('', RedirectView.as_view(url='protocols/')),
    path('protocols/', include('protocols.urls'), name='protocols'),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('privacy/', user_views.privacy, name='privacy'),
    path('profile/', user_views.profile, name='profile'),
    path('profile_settings/', user_views.profile_settings, name='profile_settings'),
    path('delete_user/', user_views.delete_user, name = 'delete_user'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/', include('allauth.urls')),
]

protocols/urls.py
from django.urls import path


from . import views

app_name = 'protocols'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('scheduler/', views.scheduler, name='scheduler'),
    path('scheduler/<int:experiment_id>/', views.scheduler_options, name='scheduler_options'),
    path('new_protocol/', views.ProtocolCreate.as_view(), name='add_protocol'),
    path('edit/<int:pk>/', views.ProtocolUpdate.as_view(), name='edit_protocol'),
    path('delete/<int:pk>/', views.ProtocolDelete.as_view(), name='delete_protocol'),
    path('new_event/', views.create_event, name='create_event'),
    path('<int:protocol_id>/', views.detail, name='detail'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/<int:event_id>/', views.event, name='event'),
    path('experiment/<int:experiment_id>/', views.experiment, name='experiment'),
    path('calendar/edit/<int:event_id>/', views.edit_event, name='event_edit'),
    path('calendar/delete/<int:event_id>/', views.delete_event, name="event_delete")
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm
from protocols.models import Protocol, Experiment
from .models import User


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created. You can now log in.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'Account is updated.')
            return redirect('profile')
    else:
        form = UserUpdateForm(instance=request.user)
    experiments = Experiment.objects.filter(created_by=request.user)
    protocols = Protocol.objects.filter(created_by=request.user)
    context = {
        'form': form,
        'experiments': experiments,
        'protocols': protocols
    }
    return render(request, 'users/profile.html', context)

@login_required
def profile_settings(request):
    return render(request, 'users/profile_settings.html', {})

@login_required
def delete_user(request):
    if request.method == 'POST':
        try:
            u = User.objects.get(id=request.user.id)
            u.delete()
            messages.success(request, "Account successfully deleted")
            return redirect('protocols:index')
        except User.DoesNotExist:
            messages.warning(request, "User does not exist")
            # return render(request, 'users/user_confirm_delete.html')

    return render(request, 'users/user_confirm_delete.html', {})

def privacy(request):
    return render(request, 'users/privacy.html', {})

users/templates/users/login.html
{% load socialaccount %}
{% include "protocols/header.html" %}

{% load crispy_forms_tags %}
{% block content %}
    <div class = "">
        <form method="POST" class = "col-md-6 mx-auto">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Log In</legend>
                {{ form | crispy}}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Log In</button>
            </div>

                <div class = "border-top pt-3">
                    <small class = "text-muted">
                        Need an Account? <a href="{% url 'register' %}" class = "ml-2">Sign Up</a>
                    </small>
                </div>
        </form>

    </div>
{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/logout.html
{% include "protocols/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2> You have been logged out </h2>
    <div class = "border-top pt-3">
        <small class = "text-muted">
            <a href="{% url 'login' %}" class = "">Log in again?</a>
        </small>
    </div>
{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/password_reset.html
{% include "protocols/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "">
        <form method="POST" class = "col-md-6 mx-auto">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Reset Password</legend>
                {{ form | crispy}}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/password_reset_confirm.html
{% include "protocols/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "">
        <form method="POST" class = "col-md-6 mx-auto">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Reset Password</legend>
                {{ form | crispy}}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/password_reset_done.html
{% include "protocols/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "alert alert-info">
        An email has been sent with instructions to reset password.
    </div>
{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/privacy.html
{% include "protocols/header.html" %}
<div class = "">
<h2>Privacy Policy</h2>

<p>Last updated: 07/24/2020</p>

<p>Experiment Scheduler operates <a href = "https://experiment-planner.herokuapp.com">https://experiment-planner.herokuapp.com</a> (the "Site"). This page informs you of
    our policies regarding the collection, use and disclosure of Personal Information we receive from users of the Site.
</p>

<p>We use your Personal Information only for providing and improving the Site. By using the Site, you agree to the
    collection and use of information in accordance with this policy.</p>

<strong>Information Collection And Use</strong>

<p>While using our Site, we may ask you to provide us with certain personally identifiable information that can be used
    to contact or identify you. Personally identifiable information may include, but is not limited to your name, email,
    and optional information including a 3rd party profile and associated email("Personal Information"). </p>

<strong>Log Data</strong>

<p>Like many site operators, we collect information that your browser sends whenever you visit our Site ("Log Data").</p>

<p>This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type,
    browser version, the pages of our Site that you visit, the time and date of your visit, the time spent on those
    pages and other statistics.</p>

<p>In addition, we may use third party services such as Google Analytics that collect, monitor and analyze this data.</p>

<strong>Communications</strong>

<p>We may use your Personal Information to contact you with newsletters, marketing or promotional materials and other
    information that pertains to the Site.</p>

<strong>Cookies</strong>

<p>Cookies are files with small amount of data, which may include an anonymous unique identifier. Cookies are sent to your
    browser from a web site and stored on your computer's hard drive.</p>

<p>Like many sites, we use "cookies" to collect information. You can instruct your browser to refuse all cookies or to
indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions
    of our Site.</p>

<strong>Security</strong>

<p>The security of your Personal Information is important to us, but remember that no method of transmission over the
Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to
    protect your Personal Information, we cannot guarantee its absolute security.</p>

<strong>Changes To This Privacy Policy</strong>

<p>This Privacy Policy is effective as of 07/24/2020 and will remain in effect except with respect to any changes in its
    provisions in the future, which will be in effect immediately after being posted on this page. </p>

<p>We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy
    periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page
    will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified
    Privacy Policy.</p>

<p>If we make any material changes to this Privacy Policy, we will notify you either through the email address you have
    provided us, or by placing a prominent notice on our website.</p>

<strong>Contact Us</strong>

<p>If you have any questions about this Privacy Policy, please contact us.</p>
</div>
{% include "protocols/footer.html" %}

users/templates/users/profile.html
{% include "protocols/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class = "">
    <h1>{{ user.username }}</h1>
    <div class = "row">
        <div class = "col-md-5">
            <legend class = "border-bottom mb-r">Experiments</legend>
            {% if experiments %}
                {% for experiment in experiments %}
            <p><a href = "{% url 'protocols:experiment' experiment.id %}">{{experiment.name}}</a></p>
                {% endfor %}
            {% endif %}

        </div>
        <div class = "col-md-5">
            <legend class = "border-bottom mb-r">Protocols</legend>

            {% if protocols %}
                {% for protocol in protocols %}
            <p><a href = "{% url 'protocols:detail' protocol.id %}">{{protocol.name}}</a></p>
                {% endfor %}
            {% endif %}
        </div>
        <small method="POST" class = "col-md-2" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Profile Info</legend>
                {{ form | crispy }}
            </fieldset>

            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Update</button>
                <a class = "btn btn-outline-secondary" href = "{% url 'profile_settings' %}">settings</a>

            </div>

        </form>

    </div>

</div>

{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/profile_settings.html
{% include "protocols/header.html" %}
{% block content %}
<div class = "">
    <h1>Profile Settings</h1>
    <a class = "btn btn-outline-secondary mt-2" href = "{% url 'socialaccount_connections' %}">manage social accounts</a>
    <a class = "btn btn-danger mt-2" href = "{% url 'delete_user' %}">delete account</a>

</div>
{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/register.html
{% include "protocols/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class = "">
        <form method="POST" class = "col-md-6 mx-auto">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class = "border-bottom mb-4">Sign Up</legend>
                {{ form | crispy}}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type="submit">Sign Up</button>
            </div>
                <div class = "border-top pt-3">
                    <small class = "text-muted">
                        Already Have an Account? <a href="{% url 'login' %}" class = "ml-2">Sign In</a>
                    </small>
                </div>
        </form>
    </div>
{% endblock content %}
{% include "protocols/footer.html" %}

users/templates/users/user_confirm_delete.html
{% include "protocols/header.html" %}
{% block content %}
<div class = "">
    <h2>Are you sure you want to delete account for <a href = "{% url 'profile' %}">{{ user.username}}</a>?</h2>
    <p>Account and all data associated with it will be permanently deleted. </p>
    <form method="POST" >
        {% csrf_token %}
        <input class = "btn btn-danger" type="submit" value="Confirm Delete">
    </form>

</div>
{% endblock content %}
{% include "protocols/footer.html" %}