experiment_planner/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import RedirectView
from users import views as user_views

urlpatterns = [
    path('', RedirectView.as_view(url='protocols/')),
    path('protocols/', include('protocols.urls'), name='protocols'),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('privacy/', user_views.privacy, name='privacy'),
    path('profile/', user_views.profile, name='profile'),
    path('profile_settings/', user_views.profile_settings, name='profile_settings'),
    path('delete_user/', user_views.delete_user, name = 'delete_user'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/', include('allauth.urls')),
]

protocols/urls.py
from django.urls import path


from . import views

app_name = 'protocols'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.about, name='about'),
    path('scheduler/', views.scheduler, name='scheduler'),
    path('scheduler/<int:experiment_id>/', views.scheduler_options, name='scheduler_options'),
    path('new_protocol/', views.ProtocolCreate.as_view(), name='add_protocol'),
    path('edit/<int:pk>/', views.ProtocolUpdate.as_view(), name='edit_protocol'),
    path('delete/<int:pk>/', views.ProtocolDelete.as_view(), name='delete_protocol'),
    path('new_event/', views.create_event, name='create_event'),
    path('<int:protocol_id>/', views.detail, name='detail'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/<int:event_id>/', views.event, name='event'),
    path('experiment/<int:experiment_id>/', views.experiment, name='experiment'),
    path('calendar/edit/<int:event_id>/', views.edit_event, name='event_edit'),
    path('calendar/delete/<int:event_id>/', views.delete_event, name="event_delete")
]

protocols/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
from datetime import date, timedelta
from .Protocol import ProtocolLinkedList, RSDStep, SDStep, TDStep


class Protocol(models.Model):
    name = models.CharField(max_length=200)
    days = models.IntegerField(default=1)
    description = models.CharField(max_length=200)
    protocol_ll = ProtocolLinkedList()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class Step(models.Model):
    protocol = models.ForeignKey(Protocol, on_delete=models.CASCADE)
    type = models.CharField(max_length=50,
                            choices=[('default', 'default'),
                                     ('SDS', 'SDS'),
                                     ('RSDS', 'RSDS'),
                                     ('TDS', 'TDS')])
    step_text = models.CharField(max_length=1000)
    time_min = models.IntegerField(default=0)
    days_between = models.IntegerField(default=1)
    gap_days = models.IntegerField(default=0)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


class Feature(models.Model):
    step = models.ForeignKey(Step, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    details = models.CharField(max_length=1000)


class Event(models.Model):
    step = models.ForeignKey(Step, on_delete=models.CASCADE, related_name="step")
    experiment_id = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    start_time = models.DateTimeField(default=timezone.now(),)
    minutes = models.IntegerField(default=5)
    notes = models.CharField(max_length=1000, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    @property
    def get_html_url(self):
        url = reverse('protocols:event', args=(self.id,))
        return f'<a href="{url}">{self.title}</a>'


class Experiment(models.Model):
    protocol = models.ForeignKey(Protocol, on_delete=models.CASCADE)
    earliest_start = models.DateTimeField(default=timezone.now())
    latest_start = models.DateTimeField(default=timezone.now() + timedelta(days=14))
    name = models.CharField(max_length=200)
    date = models.DateTimeField(default=timezone.now())
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

protocols/forms.py
from django.forms import ModelForm, DateInput
from .models import Event, Experiment, Protocol, Step
from datetime import datetime
from django.forms.models import inlineformset_factory
from django import forms


class EventForm(ModelForm):
    notes = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Event
        widgets = {
            'start_time': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')
        }
        fields = ['title', 'start_time', 'minutes', 'notes']

        def __init__(self, *args, **kwargs):
            super(EventForm, self).__init__(*args, **kwargs)
            self.fields['start_time'].input_formats = ('%Y-%m-%d',)


class ExperimentForm(ModelForm):

    class Meta:
        model = Experiment
        widgets = {
            'earliest_start': DateInput(attrs={'type': 'date', 'value': datetime.now().strftime('%Y-%m-%d')}, format='%Y-%m-%d'),
            'latest_start': DateInput(attrs={'type': 'date', 'value': datetime.now().strftime('%Y-%m-%d')}, format='%Y-%m-%d'),
            'date': DateInput(attrs={'type': 'date', 'value': datetime.now().strftime('%Y-%m-%d')}, format='%Y-%m-%d')
        }
        fields = '__all__'
        exclude = ['created_by']

        def __init__(self, *args, **kwargs):
            super(ExperimentForm, self).__init__(*args, **kwargs)
            self.fields['earliest_start'].input_formats = ('%Y-%m-%d',),
            self.fields['latest_start'].input_formats = ('%Y-%m-%d',)
            self.fields['protocol'].queryset = (Protocol.objects.filter(created_by=self.created_by))
#
#
# class ProtoclForm(ModelForm):
#     class Meta:
#         model = Protocol
#         fieldsets = [
#             (None, {'fields': ['name']}),
#             ('Days', {'fields': ['days']}),
#             ('Description', {'fields': ['description']})
#         ]
#         inlines = [StepInline]
#         list_display = ('name', 'description', 'days')
#         search_fields = ['name']


class StepForm(ModelForm):
    class Meta:
        model = Step
        exclude = ()


StepFormSet = inlineformset_factory(Protocol, Step, form=StepForm, fields='__all__', exclude=['created_by'], extra=3, can_delete=True)

protocols/views.py
from datetime import date, datetime, timedelta
import calendar
import plotly.graph_objects as go
import plotly.offline as opy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.safestring import mark_safe
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db import transaction
from django.urls import reverse_lazy
from .Protocol import ProtocolLinkedList, RSDStep, SDStep, TDStep
from .forms import *
from .models import Event, Experiment, Protocol, Step
import json
from .utils import *


class CalendarView(ListView):
    model = Event
    template_name = 'protocols/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def create_event(request):
    form = EventForm()
    context = {
        'form': form,
    }
    return render(request, 'protocols/new_event.html', context)


def edit_event(request, event_id):
    template_name = 'protocols/event_edit.html'
    event = get_object_or_404(Event, pk=event_id)
    experiment = get_object_or_404(Experiment, pk=event.experiment_id)
    # Form
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event = form.save()
            return redirect('protocols:event', event_id=event.id)
    else:
        form = EventForm(instance=event)

    context = {
        'event': event,
        'experiment': experiment,
        'form': form
    }
    return render(request, template_name, context)


def about(request):
    template_name = 'protocols/about.html'
    return render(request, template_name)


def delete_event(request, event_id):
    template_name = 'protocols/event_delete.html'
    event = get_object_or_404(Event, pk=event_id)
    context = {
        'event': event
    }

    if "one" in request.POST:
        Event.objects.get(pk=event_id).delete()  # delete event
        return redirect('protocols:index')
    elif "all" in request.POST:
        Event.objects.filter(experiment_id=event.experiment_id).delete()  # delete all events in experiment
        Experiment.objects.filter(pk=event.experiment_id).delete() # delete experiment
        return redirect('protocols:index')

    return render(request, template_name, context)


def event(request, event_id):
    template_name = 'protocols/event.html'
    context_object_name = 'event'
    event = get_object_or_404(Event, pk=event_id)
    experiment = get_object_or_404(Experiment, pk=event.experiment_id)
    context = {
        context_object_name: event,
        'experiment': experiment
    }
    return render(request, template_name, context)


@login_required
def scheduler(request):
    if request.method == 'POST':
        experiment = Experiment()
        form = ExperimentForm(request.POST, instance=experiment)
        if form.is_valid():
            experiment.created_by = request.user
            experiment = form.save()
            return redirect('protocols:scheduler_options', experiment_id=experiment.id)
    else:
        experiment = Experiment()
        experiment.created_by = request.user
        form = ExperimentForm(instance=experiment)
        form.fields['protocol'].queryset = Protocol.objects.filter(created_by=request.user)
        # form['protocol'].queryset = Protocol.objects.filter(created_by=request.user)
    template_name = 'protocols/scheduler.html'
    context = {
        'form': form
    }
    return render(request, template_name, context)


@login_required
def scheduler_options(request, experiment_id):
    template_name = 'protocols/scheduler_options.html'
    experiment = get_object_or_404(Experiment, pk=experiment_id)
    protocol_ll = protocol_to_protocol_ll(experiment.protocol)
    num_days = protocol_ll.total_days()  # max number of days in protocol
    start_range = experiment.latest_start - experiment.earliest_start
    start = experiment.earliest_start
    end = experiment.latest_start + timedelta(days=num_days + 1)
    sched_len = end - start
    events = Event.objects.filter(start_time__gte=start, start_time__lte=end)
    schedule_objs = build_schedule(start, sched_len.days, events)
    scores = score_alignments(protocol_ll, schedule_objs, start_range.days)
    formated_scores = []
    x = []
    y = []
    for score in scores:
        x.append(str(score[0].date()))
        y.append(score[1])
    fig = go.Figure([go.Bar(x=x, y=y)])
    fig.update_layout(
        title={
            'text': 'Scores for each start date',
            'y':0.9,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'
        }
    )
    div = opy.plot(fig, auto_open=False, output_type='div')

    # Form
    if request.method == 'POST':
        form = ExperimentForm(request.POST, instance=experiment)
        if form.is_valid():
            experiment = form.save()
            if 'add_calendar' in request.POST:
                schedule_objs_events = build_schedule(experiment.date, sched_len.days, events)

                #TODO add to calendar logic here
                d, n = protocol_ll.build_DAG()
                add_experiment_to_calendar(experiment, d, n, schedule_objs_events, request.user)
                return redirect('protocols:index')
            return redirect('protocols:scheduler_options', experiment_id=experiment.id)
    else:
        form = ExperimentForm(instance=experiment)
    # Context
    context = {
        'experiment': experiment,
        'schedule': schedule_objs,
        'graph': div,
        'form': form
    }
    return render(request, template_name, context)


def index(request):
    """"index view"""
    template_name = 'protocols/index.html'
    context_object_name = 'protocol_list'
    return render(request, template_name, {context_object_name: Protocol.objects.all()})


class IndexView(ListView):
    """Index view containing calendar"""
    template_name = 'protocols/index.html'
    context_object_name = 'protocol_list'
    model = Protocol

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        if self.request.user.is_authenticated:
            context['protocol_list'] = Protocol.objects.filter(created_by=self.request.user)
            context['events'] = Event.objects.filter(start_time__date=datetime.now(), created_by=self.request.user)
            cal = Calendar(d.year, d.month, self.request.user)
        else:
            cal = Calendar(d.year, d.month)
            context['protocol_list'] = []

        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def detail(request, protocol_id):
    """detail view"""
    template_name = "protocols/detail.html"
    context_object_name = 'protocol'
    protocol = get_object_or_404(Protocol, pk=protocol_id)
    steps = Step.objects.filter(protocol=protocol) #get all step associated with protocol
    protocol_ll = protocol_to_protocol_ll(protocol) #updates dag in protocol
    dag, nodes = protocol_ll.build_DAG()
    json = format_dag_json(dag, nodes)
    context = {
        'protocol': protocol,
        'json': json

    }

    return render(request, template_name, context)


def experiment(request, experiment_id):
    template_name = 'protocols/experiment.html'
    experiment = get_object_or_404(Experiment, pk=experiment_id)
    events = Event.objects.filter(experiment_id=experiment_id)
    context = {
        'experiment': experiment,
        'events': events
    }
    return render(request, template_name, context)


class ProtocolCreate(LoginRequiredMixin, CreateView):
    model = Protocol
    template_name = 'protocols/add_protocol.html'
    fields = ['name', 'description']
    success_url = None

    def get_context_data(self, **kwargs):
        data = super(ProtocolCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            data['steps'] = StepFormSet(self.request.POST)
        else:
            data['steps'] = StepFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        steps = context['steps']
        form.instance.created_by = self.request.user
        with transaction.atomic():
            self.object = form.save()

            if steps.is_valid():
                steps.instance = self.object
                steps.save()
        return super(ProtocolCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('protocols:detail', kwargs={'protocol_id': self.object.pk})


class ProtocolUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Protocol
    template_name = 'protocols/add_protocol.html'

protocols/templates/protocols/about.html
{% include "./header.html" %}
<div class = "main">
    <div class="jumbotron">
  <h1 class="display-4">Hello!</h1>
  <p class="lead">Experiment Scheduler finds the best days to start a multi-day protocol to avoid over-scheduling any one day and avoid weekends.</p>
  <hr class="my-4">
  <p>You can add custom protocols and schedule them over range of dates to best meet your schedule.</p>
  <p class="lead">
    <a class="btn btn-success btn-lg" href="{% url 'account_login' %}" role="button">Get Started</a>
  </p>
</div>
</div>
{% include "./footer.html" %}

protocols/templates/protocols/add_protocol.html
{% include "./header.html" %}
{% load crispy_forms_tags %}

<div class = "main">
    <div class = "form ">
        <form action="" method="post">{% csrf_token %}
            {{ form |crispy }}
            <table class="table table-responsive-sm">
                {{ steps.management_form }}

                {% for form in steps.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>{{ field.label|capfirst }}</th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr id="">
                        {% for field in form.visible_fields %}
                            <td>
                                {# Include the hidden fields in the form #}
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>

                {% endfor %}

            </table>

            <input class = "btn btn-success" type="submit" value="Save"/>
            <input type="button" value="Add Step" id="add_more" class = "btn btn-success">
            {% if object %}
            <a class = "btn btn-danger" href="{% url 'protocols:delete_protocol' object.pk %}">Delete</a>
            <a class = "btn btn-secondary" href = "{% url 'protocols:detail' object.pk %}">Back</a>
            {% endif %}
        </form>
    </div>
</div>
{% include "./footer.html" %}

<script type='text/javascript'>
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    console.log('#id_' + prefix + '-TOTAL_FORMS')
    var total = document.getElementById('id_' + prefix + '-TOTAL_FORMS').value;
    console.log(total);
    newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
        console.log('_' + (total-1) + '-');
        var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
    });
    newElement.find('label').each(function() {
        var forValue = $(this).attr('for');
        if (forValue) {
          forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
          $(this).attr({'for': forValue});
        }
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    <!--var conditionRow = $('.form-row:not(:last)');-->
    <!--conditionRow.find('.btn.add-form-row')-->
    <!--.removeClass('btn-success').addClass('btn-danger')-->
    <!--.removeClass('add-form-row').addClass('remove-form-row')-->
    <!--.html('<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>');-->
    <!--return false;-->
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.form-row').remove();
        var forms = $('.form-row');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '#add_more', function(e){
    e.preventDefault();
    cloneMore('tr:last', 'step_set');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('form', $(this));
    return false;
});
</script>

protocols/templates/protocols/calendar.html
{% include "./header.html" %}
    <div class = "main">
        {% block content %}
        <a href="{% url 'protocols:calendar' %}?{{ prev_month }}"> Previous Month </a><a href="{% url 'protocols:calendar' %}?{{ next_month }}"> Next Month </a>
        {{ calendar }}
        {% endblock %}
    </div>
{% include "./footer.html" %}

protocols/templates/protocols/delete_protocol.html
{% include "./header.html" %}

    <div class = "main">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"? Any scheduled events for this protocol will also be deleted.</p>
            <input type="submit" value="Confirm"/> <a href = "{% url 'protocols:edit_protocol' object.id %}">Back</a>
        </form>
    </div>
{% include "./footer.html" %}

protocols/templates/protocols/detail.html
{% include "./header.html" %}
    <div id = "details" class = "">
        <div class = "white-background">
        <h1>{{protocol.name}}</h1>

        <p>{{protocol.description}}</p>
        <p>{{protocol.created_by}}</p>
        <table class="white-background table table-responsive-sm">
            <tr>
                <th><strong>Step</strong></th>
                <th><strong>Minutes</strong></th>
                <th><strong>Days between steps</strong></th>
                <th><strong>Days from start</strong></th>
                <th><strong>Gap Tolerance? (Days) </strong></th>
            </tr>
            {% for step in protocol.step_set.all %}
                <tr>
                    <td class = "text-left">{{step.step_text}}</td>
                    <td>{{step.time_min}}</td>
                    {% if step.type == "TDS" %}
                        <td>--</td>
                        <td>{{step.days_between}}</td>
                    {% else %}
                        <td>{{step.days_between}}</td>
                        <td>--</td>
                    {% endif %}
                    <td>{{step.gap_days}}</td>
                </tr>
                {% for feature in step.feature_set.all %}
                    <tr>
                        <td></td>
                        <td>{{feature.name}} + '\n' + {{feature.details}}</td>
                        <td></td>
                    </tr>
                {% endfor %}
            {% endfor %}

        </table>
            <a class = 'btn btn-secondary' href = "{% url 'protocols:edit_protocol' protocol.id %}">Edit</a>
<!--        <h2>DAG:</h2>
        <div>
            {% for node in protocol.dag %}
                <p>{{node}}</p>
            {% endfor %}
        </div>
        </div>-->
    </div>

{% include "./footer.html" %}

protocols/templates/protocols/event_delete.html
{% include "./header.html" %}

    <div class = "main">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ event }}" event?</p>
            <p>Chose between deleting this event only or deleting all events in this experiment. </p>
            <div id = "event_delete">
                <input class = "btn btn-warning" type="submit" name = "one" value="Delete One"/><input class = "btn btn-danger" type="submit" name = "all" value="Delete All"/><a class = "btn btn-secondary" href = "{% url 'protocols:event_edit' event.id %}">Back</a>
            </div>

        </form>
    </div>
{% include "./footer.html" %}

protocols/templates/protocols/event_edit.html
{% include "./header.html" %}
{% load crispy_forms_tags %}
<div class = "main">
    <div class = "events card">
        <div class = "card-header">
            <h4 class = "">{{event.title}}</h4>
        </div>
        <div class = "card-body">

            <div class = "card-text">
                <form action="" method="post">{% csrf_token %}
                    {{ form | crispy}}
                    <input class = "btn btn-success" type="submit" value="Save"/>
                    <a class = "btn btn-danger" href="{% url 'protocols:event_delete' event.pk %}">Delete</a>
                </form>
            </div>

        </div>
    </div>
</div>
{% include "./footer.html" %}

protocols/templates/protocols/footer.html
</div>

protocols/templates/protocols/header.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'protocols/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.3.1-dist/bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="{% static 'jquery-3.5.0.js' %}"></script>
<script src="{% static 'bootstrap-4.3.1-dist/bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
<script src="https://apis.google.com/js/api:client.js"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>
    <nav class = "navbar sticky-top" id = "navbar">
            <div class = "navbar-header">
                <a class = "navbar-brand" href="{% url 'protocols:index'%}">
                    <i class="fa fa-flask" aria-hidden="true"></i>
                    Experiment Scheduler
                </a>
            </div>

            <a id = "schedule-btn" class = "btn btn-sm btn-light ml-auto" href="{% url 'protocols:scheduler' %}">
                <i class="fa fa-calendar-plus-o" aria-hidden="true"></i>
                 Schedule
            </a>
            {% if user.is_authenticated %}
                <a id = "profile-btn" class = "btn btn-sm btn-outline-light ml-2" href="{% url 'profile' %}">
                    <i class="fa fa-user" aria-hidden="true"></i>
                     {{ user.username }}
                </a>
                <a id = "logout-btn" class = "btn btn-sm btn-outline-light ml-2" href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <!--<a id = "login-btn" class = "btn btn-sm btn-outline-light ml-2" href="{% url 'account_signup' %}">Sign Up</a>-->
            <a id = "signup-btn" class = "btn btn-sm btn-outline-light ml-2" href="{% url 'account_login' %}">Sign In</a>
            {% endif %}
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class = "alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class = "container-fluid">

protocols/templates/protocols/index.html
{% include "./header.html" %}
<!-- header -->
    <div id = "index-main" class = "main row">
        <div class = "col">
            <div class = "">
                <h3>Current Tasks:</h3>
                {% if events %}
                    <!--<table class="white-background">
                        <tr>
                            <th><strong>Protocol</strong></th>
                            <th><strong>Days</strong></th>
                        </tr>-->
                    <div class = "list-group">
                        {% for event in events %}
                            <a class="list-group-item list-group-item-action" href="{% url 'protocols:event' event.id %}">{{event.title}}</a>
                        {% endfor %}
                    </div>
                        <!--</table>-->
                {% else %}
                    {% if user.is_authenticated %}
                    <p>There are no steps scheduled today</p>
                    {% else %}
                        <div class = "list-group">
                            <a class="list-group-item list-group-item-action" href="{% url 'protocols:about' %}">Learn about optimal scheduling</a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
            <div>
                <h3>Protocols:</h3>
            {% if protocol_list %}
                <!--<table class="white-background">
                    <tr>
                        <th><strong>Protocol</strong></th>
                        <th><strong>Days</strong></th>
                    </tr>-->
                <div class = "list-group">
                    {% for protocol in protocol_list %}
                        <a class = "list-group-item list-group-item-action" href="{% url 'protocols:detail' protocol.id %}">{{protocol.name}}</a>
                    {% endfor %}

                        <a  class = "btn list-group-item list-group-item-light"  href = "{% url 'protocols:add_protocol' %}">+ add protocol</a>

                </div>
                    <!--</table>-->
            {% else %}
                <a class = "list-group-item list-group-item-light" href = "{% url 'protocols:add_protocol' %}">+ add protocol</a>
            {% endif %}

            </div>

        </div>

        <div class = "calendar-container col-9">
            <div>
                <h3>Calendar:<span style="float:right;" ><a class = 'month-btn btn btn-secondary btn-sm' href="{% url 'protocols:index' %}?{{ prev_month }}"> << </a><a class = 'month-btn btn btn-secondary btn-sm' href="{% url 'protocols:index' %}?{{ next_month }}"> >> </a></span></h3>
            </div>
            <div>
                {{calendar}}
            </div>
        </div>

    </div>
{% include "./footer.html" %}

protocols/templates/protocols/new_event.html
{% include "./header.html" %}
<div class = "main">
    <div class = "events">
        {{form}}
    </div>
</div>
{% include "./footer.html" %}